### ISSUE TITLE
Add unit test with PHPUnit

### ISSUE THREAD

**Issue by peter279k** [riesenia/utility#6]
As title. If possible, can we let this package add the unit test with PHPUnit?

**Comment by segy** [comment]
hi. any problems with phpspec or what exact tests are you missing here? thanks

**Comment by peter279k** [comment]
@segy, thank you for your reply.
The `phpspec` is for the BDD test and the `phpunit` is for the unit test.
They're different test and I want to let this package have the unit test.

Thanks.

**Comment by segy** [comment]
ok. any pr on this is welcome
